### PR TITLE
coordinate scalers during SAXS & WAXS

### LINKED ISSUE #568: Fix scalers with SAXS/WAXS
We have unexpected behavior of our S/WAXS code. 
We expect that scaler0 and scaler1 collect I0 (ungated and gated) during AD exposure. 

In our **scans.py** our code sets time in lines 849-865 parameters needed for this collection. Lines 867/869 triggers the data collection on scaler0 and scaler1. Lines 865-899 stop counting and collect I0 values for AD to save in Nexus writer. 

Unluckily, this fails: Currently we set the values and trigger the scalers counting, but BS seems to stop scaler0 and scaler1 counting during SAXS/SAXS AD data collection. So we hav eshort counting before AD triggers and short collection after it triggers, but we completely miss the time when we need these scalers to be collecting data. 

I suspect that BS (bps.count) stops the scaler0 and scaler1 during the counting since it is not instructed to collect the data on them and does not ignore them as  spec used to so (and BS used to do in prior incarnation) .

### LINKED ISSUE #570: RE.abort() needs to remove suspenders
RE.abort() does not seem to remove suspenders and operations which do not require beam are still impossible after RE.abort() without beam. RE.abort() should remove the suspenders.

### PR DESCRIPTION
**Pull request by prjemian**
- closes #568
- closes #570

### CODE REVIEW

**Comment by prjemian** [comment]
Just the SAXS plan is refactored.  We'll need to test for the problem with the scalers.  Once that is cleared, we can refactor the WAXS plan in the same style.

**Review by jilavsky — CHANGES_REQUESTED** [review]
For the suspender, by removing the white beam suspender, we also removed the 100sec delay and hook to start feedback. Can we add the hook which starts feedback before the 100sec delay in the BeamInHutch and then run the 100sec delay? I think that is the logical thing...If you get beam back, start feedback and run feedback for 100 seconds.

**Comment by jilavsky** [comment]
I like the recasting of the SAXS code. Looks lot more logical and cleaner. Let's try it tomorrow, if possible.

**Comment by prjemian** [comment]
> For the suspender, by removing the white beam suspender, we also removed the 100sec delay and hook to start feedback. Can we add the hook which starts feedback before the 100sec delay in the BeamInHutch and then run the 100sec delay? I think that is the logical thing...If you get beam back, start feedback and run feedback for 100 seconds.

Since removing the suspender has additional consequences that venture outside the realm of #568, I plan to revert commit 0c25f48 and make all the the suspender changes as part of a PR based on #566 & #570.

**Pull request closed without merging**
